#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

namespace YSTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IdleInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IdleInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IdleInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DodgeInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DodgeInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DodgeInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(JustAvoidInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(JustAvoidInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(JustAvoidInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FallingInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FallingInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FallingInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReadyInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReadyInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReadyInputAttack);
}
