#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

namespace YSTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IdleInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IdleInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IdleInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IdleInputDodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IdleInputJump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IdleInputSprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackInputDodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackInputJump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackInputSprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DodgeInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DodgeInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DodgeInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DodgeInputDodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DodgeInputJump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DodgeInputSprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(JustAvoidInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(JustAvoidInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(JustAvoidInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(JustAvoidInputDodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(JustAvoidInputJump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(JustAvoidInputSprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FallingInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FallingInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FallingInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FallingInputDodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FallingInputJump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FallingInputSprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillInputDodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillInputJump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillInputSprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReadyInputMove);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReadyInputLook);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReadyInputAttack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReadyInputDodge);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReadyInputJump);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReadyInputSprint);
}
