#include "General/YSGeneratedGameplayTags.h"

namespace YSTags
{
	UE_DEFINE_GAMEPLAY_TAG(IdleInputMove, "Idle.Input.Move");
	UE_DEFINE_GAMEPLAY_TAG(IdleInputLook, "Idle.Input.Look");
	UE_DEFINE_GAMEPLAY_TAG(IdleInputAttack, "Idle.Input.Attack");
	UE_DEFINE_GAMEPLAY_TAG(IdleInputDodge, "Idle.Input.Dodge");
	UE_DEFINE_GAMEPLAY_TAG(IdleInputJump, "Idle.Input.Jump");
	UE_DEFINE_GAMEPLAY_TAG(IdleInputSprint, "Idle.Input.Sprint");
	UE_DEFINE_GAMEPLAY_TAG(AttackInputMove, "Attack.Input.Move");
	UE_DEFINE_GAMEPLAY_TAG(AttackInputLook, "Attack.Input.Look");
	UE_DEFINE_GAMEPLAY_TAG(AttackInputAttack, "Attack.Input.Attack");
	UE_DEFINE_GAMEPLAY_TAG(AttackInputDodge, "Attack.Input.Dodge");
	UE_DEFINE_GAMEPLAY_TAG(AttackInputJump, "Attack.Input.Jump");
	UE_DEFINE_GAMEPLAY_TAG(AttackInputSprint, "Attack.Input.Sprint");
	UE_DEFINE_GAMEPLAY_TAG(DodgeInputMove, "Dodge.Input.Move");
	UE_DEFINE_GAMEPLAY_TAG(DodgeInputLook, "Dodge.Input.Look");
	UE_DEFINE_GAMEPLAY_TAG(DodgeInputAttack, "Dodge.Input.Attack");
	UE_DEFINE_GAMEPLAY_TAG(DodgeInputDodge, "Dodge.Input.Dodge");
	UE_DEFINE_GAMEPLAY_TAG(DodgeInputJump, "Dodge.Input.Jump");
	UE_DEFINE_GAMEPLAY_TAG(DodgeInputSprint, "Dodge.Input.Sprint");
	UE_DEFINE_GAMEPLAY_TAG(JustAvoidInputMove, "JustAvoid.Input.Move");
	UE_DEFINE_GAMEPLAY_TAG(JustAvoidInputLook, "JustAvoid.Input.Look");
	UE_DEFINE_GAMEPLAY_TAG(JustAvoidInputAttack, "JustAvoid.Input.Attack");
	UE_DEFINE_GAMEPLAY_TAG(JustAvoidInputDodge, "JustAvoid.Input.Dodge");
	UE_DEFINE_GAMEPLAY_TAG(JustAvoidInputJump, "JustAvoid.Input.Jump");
	UE_DEFINE_GAMEPLAY_TAG(JustAvoidInputSprint, "JustAvoid.Input.Sprint");
	UE_DEFINE_GAMEPLAY_TAG(FallingInputMove, "Falling.Input.Move");
	UE_DEFINE_GAMEPLAY_TAG(FallingInputLook, "Falling.Input.Look");
	UE_DEFINE_GAMEPLAY_TAG(FallingInputAttack, "Falling.Input.Attack");
	UE_DEFINE_GAMEPLAY_TAG(FallingInputDodge, "Falling.Input.Dodge");
	UE_DEFINE_GAMEPLAY_TAG(FallingInputJump, "Falling.Input.Jump");
	UE_DEFINE_GAMEPLAY_TAG(FallingInputSprint, "Falling.Input.Sprint");
	UE_DEFINE_GAMEPLAY_TAG(SkillInputMove, "Skill.Input.Move");
	UE_DEFINE_GAMEPLAY_TAG(SkillInputLook, "Skill.Input.Look");
	UE_DEFINE_GAMEPLAY_TAG(SkillInputAttack, "Skill.Input.Attack");
	UE_DEFINE_GAMEPLAY_TAG(SkillInputDodge, "Skill.Input.Dodge");
	UE_DEFINE_GAMEPLAY_TAG(SkillInputJump, "Skill.Input.Jump");
	UE_DEFINE_GAMEPLAY_TAG(SkillInputSprint, "Skill.Input.Sprint");
	UE_DEFINE_GAMEPLAY_TAG(ReadyInputMove, "Ready.Input.Move");
	UE_DEFINE_GAMEPLAY_TAG(ReadyInputLook, "Ready.Input.Look");
	UE_DEFINE_GAMEPLAY_TAG(ReadyInputAttack, "Ready.Input.Attack");
	UE_DEFINE_GAMEPLAY_TAG(ReadyInputDodge, "Ready.Input.Dodge");
	UE_DEFINE_GAMEPLAY_TAG(ReadyInputJump, "Ready.Input.Jump");
	UE_DEFINE_GAMEPLAY_TAG(ReadyInputSprint, "Ready.Input.Sprint");
}
